### ISSUE TITLE
Add -> yaw/RPY conversions as well

### ISSUE THREAD

**Issue by helenol** [ethz-asl/minkindr_ros#2]
For @PascalGohl :)

As always, though, the usual question: WHICH ROTATION CONVENTION?

**Comment by helenol** [comment]
Resolved in mav_comm; now have yawFromQuaternion() functions there.

**Comment by PascalGohl** [comment]
thanks Helen, you are my hero.

**Comment by helenol** [comment]
Just wait until I lose more stuff from your desk. ;)
